---
- name: Tasks by blocks - ID Helix format validation
  block:
    - set_fact:
        run_playbook: |
          {% if action == 'Configurar_NetBackup' %}
          ['s0chkidhelix','s1chknbfileversion']
          {% else %}
          ['No_selecciono_ninguna_tarea']
          {% endif %}
    
    - name: Select Result
      become: true
      assert:
        that:
          - "'No_selecciono_ninguna_tarea' not in run_playbook"
        fail_msg: "run_playbook"
        success_msg: "Ha seleccionado la tarea: {{ action }}"
      run_once: true
      delegate_to: localhost
    
    - name: Start the task {{ run_playbook }}
      include_tasks: "{{ asbpbact }}.yml"
      loop: "{{ run_playbook }}"
      loop_control:
        loop_var: asbpbact
