---
- block:
    - set_fact:
        run_playbook: |
          {% if applies_certs %}
          "NetBackup es mayor a 8.2"
          {% else %}
          "NetBackup es menor a 8.2"
          {% endif %}
    
    # - name: Ejecutar tareas NetBackup
    #   include_tasks: "{{ asbpbact2 }}.yml"
    #   loop: "{{ run_playbook | from_yaml }}"
    #   loop_control:
    #     loop_var: asbpbact2

    # - name: Limpiar caché de NetBackup (Paso 2.3)
    #   ansible.builtin.command: /usr/openv/netbackup/bin/bpclntcmd -clear_host_cache
    #   changed_when: false

    # - name: Añadir Certificado CA del Master Server (Paso 2.4 - Versión >= 8.2)
    #   ansible.builtin.shell: printf 'y\n' | /usr/openv/netbackup/bin/nbcertcmd -getCaCertificate -server vxnbucfs
    #   register: get_ca_cert
    #   when: applies_certs
    #   failed_when: false

    # - name: Asociar Certificado y Token al Cliente (Paso 2.5 - Versión >= 8.2)
    #   ansible.builtin.command: /usr/openv/netbackup/bin/nbcertcmd -host {{ client_nbu_name }} -getCertificate -server vxnbucfs -token {{ cfs_token }}
    #   register: get_host_cert
    #   when: applies_certs
    #   failed_when: false

    # - name: Limpiar caché de NetBackup (Paso 2.6 - Versión >= 8.2)
    #   ansible.builtin.command: /usr/openv/netbackup/bin/bpclntcmd -clear_host_cache
    #   when: applies_certs
    #   changed_when: false