---
- block:
    - name: Validar comunicación con Master Server (bpclntcmd -pn)
      ansible.builtin.command: /usr/openv/netbackup/bin/bpclntcmd -pn
      register: bpclntcmd_pn
      changed_when: false
      failed_when: false