---
- block:
    # - name: Generar reporte HTML de Certificación CFS
    #   template:
    #     src: templates/certificacion_cfs_report.html.j2
    #     dest: "/tmp/certificacion_cfs_{{ inventory_hostname }}.html"
    #   delegate_to: localhost
    #   become: false

    - name: Generar Reporte Consolidado HTML para todos los nodos
      template:
        src: templates/consolidated_cfs_report.html.j2
        dest: "/tmp/reporte_consolidado_cfs.html"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Enviar correo único con el Reporte Ejecutivo Consolidado
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        from: "{{ email_sender }}"
        to: "{{ email_recipients }}"
        subject: "[RESUMEN EJECUTIVO] Certificación NetBackup CFS - ({{ hostvars[ansible_play_hosts[0]]['ansible_date_time']['date'] }})"
        body: "{{ lookup('file', '/tmp/reporte_consolidado_cfs.html') }}"
        subtype: html
      delegate_to: localhost
      run_once: true
      become: no


    - name: Leer Reporte Consolidado HTML para todos los nodos
      shell: cat /tmp/reporte_consolidado_cfs.html
      register: htmlrepotr
      delegate_to: localhost
      run_once: true
      become: false

    - set_fact:
        htmlrepotsf: "{{ htmlrepotr.stdout_lines }}"

- block:
    - copy:
        content: "{{ htmlrepotsf | join('\n') }}"
        dest: /tmp/reporte_consolidado_cfs.html
  run_once: true
  delegate_to: lvdasb5gmx02.bvm.bluecare.kyndryl.net
        