---
- block:
    # - name: Generar reporte HTML de Certificación CFS
    #   template:
    #     src: templates/certificacion_cfs_report.html.j2
    #     dest: "/tmp/certificacion_cfs_{{ inventory_hostname }}.html"
    #   delegate_to: localhost
    #   become: false

    - name: Generar Reporte Consolidado HTML para todos los nodos
      template:
        src: templates/consolidated_cfs_report.html.j2
        dest: "/tmp/reporte_consolidado_cfs.html"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Leer Reporte Consolidado HTML para todos los nodos
      shell: cat /tmp/reporte_consolidado_cfs.html
      register: htmlrepotr
      delegate_to: localhost
      run_once: true
      become: false

    - set_fact:
        htmlrepotsf: "{{ htmlrepotr.stout_lines }}"

- block:
    - copy:
        content: "{{ htmlrepotsf | join('\n') }}"
        dest: /tmp/reporte_consolidado_cfs.html
  delegate_to: lvdasb5gmx02.bvm.bluecare.kyndryl.net
        