---
- block:
    - name: Leer versión del cliente NetBackup
      command: cat /usr/openv/netbackup/bin/version
      register: nbchkrfv
      changed_when: false

    - name: Formatear versión de NetBackup
      set_fact:
        nbchkrfc: "{{ nbchkrfv.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+|[0-9]+\\.[0-9]+\\.[0-9]+)') }}"

    - name: Evaluar si requiere gestión de certificados (Versión >= 8.2)
      set_fact:
        applies_certs: "{{ nbchkrfc is version('8.2', '>=') }}"

    - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
      set_fact:
        nbkchpiprbt: >-
          {{
            ansible_all_ipv4_addresses
            | select('regex', '^172[.](10|11|13)[.]')
            | list
          }}

    - name: Definir sufijo de cliente (_nbu o sin sufijo)
      set_fact:
        nbcltsfx: "{{ ansible_hostname ~ '_nbu' if nbkchpiprbt[0].startswith('172.') else ansible_hostname }}"