---
- block:
    - name: Crear directorio /usr/openv/netbackup/bin NetBackup
      file:
        path: "{{ nbbin }}"
        state: directory
        mode: '0755'

    - name: Agregar contenido version NetBackup
      lineinfile:
        path: /usr/openv/netbackup/bin/version
        line: "NetBackup RedHat3.0.76 7.7.2"
        create: true
        mode: '0755'
  become: true