---
- block:
    - name: Obtener version comando NetBackup
      become: true
      shell: "{{ nbgetconfig | {{ nbparam }}"
      register: nbchkcv
      args:
        chdir: "{{ nbbin }}"
      changed_when: false

    - name: Formatear versión de NetBackup
      set_fact:
        nbchkrfc: "{{ nbchkcv.stdout | trim }}"

    - name: Evaluar si requiere gestión de certificados (Versión >= 8.2)
      set_fact:
        applies_certs: "{{ nbcversion is version('8.2', '>=') }}"
