---
- block:
    - name: Obtener version comando NetBackup
      become: true
      shell: "nbgetconfig | {{ nbparam }}"
      register: nbchkcv
      args:
        chdir: "{{ nbbin }}"
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/openv/netbackup/bin:{{ ansible_env.PATH }}"
      changed_when: false

    - name: Formatear versión de NetBackup
      set_fact:
        nbcversion: "{{ nbchkcv.stdout | trim }}"

    - name: Evaluar si requiere gestión de certificados (Versión >= 8.2)
      set_fact:
        applies_certs: "{{ nbcversion is version('8.2', '>=') }}"

