---
- block:
    - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
      set_fact:
        nbkchpiprbt: >-
          {{
            ansible_all_ipv4_addresses
            | select('regex', '^172[.](10|11|13)[.]')
            | list
          }}

    - name: Definir sufijo de cliente (_nbu o sin sufijo)
      set_fact:
        nbcltsfx: "{{ ansible_hostname ~ '_nbu' if nbkchpiprbt[0].startswith('172.') else ansible_hostname }}"

    - name: Tercera condición, validar IP Robótica o IP Servicio
      set_fact:
        run_playbook: |
          {% if nbkchpiprbt[0].startswith('172.10') %}
          ['s7bckfilehosts','s8prgfilehosts','s9addnbhf17210','s10bcknbbpconf','s11addnbmcbpconf']
          {% elif nbkchpiprbt[0].startswith('172.11') %}
          ['s7bckfilehosts','s8prgfilehosts','s9addnbhf17211','s10bcknbbpconf','s11addnbmcbpconf']
          {% elif nbkchpiprbt[0].startswith('172.13') %}
          ['s7bckfilehosts','s8prgfilehosts','s10addnbhf17213','s10bcknbbpconf','s11addnbmcbpconf']
          {% elif nbkchpiprbt[0].startswith('150.') %}
          ['s7bckfilehosts','s8prgfilehosts','s9addnbhf150xxx','s10bcknbbpconf','s11addnbmcbpconf']
          {% else %}
          ['s5msgnbcmfailed']
          {% endif %}
    
    - name: Ejecutar tareas NetBackup
      include_tasks: "{{ asbpbact3 }}.yml"
      loop: "{{ run_playbook | from_yaml }}"
      loop_control:
        loop_var: asbpbact3
