---
- block:
    # - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
    #   set_fact:
    #     nbkchpiprbt: >-
    #       {{
    #         ansible_all_ipv4_addresses
    #         | select('regex', '^172[.](10|11|13)[.]')
    #         | list
    #       }}

    - name: Actualizar /etc/hosts para equipos sin IP Robótica (150.100.x.x)
      blockinfile:
        path: "{{ filehosts }}"
        marker: "# {mark} ANSIBLE MANAGED NETBACKUP CFS DATA IP"
        block: |
          172.13.103.137 vxnbucfs
          172.13.103.136 cpdnbumedia3-le
          172.13.103.176 cpdnbumedia6-le
          172.10.120.132 lvprpbckrescc01-cfs
          {{ nbkchpiprbt | first }} {{ nbcltsfx }}
      when: 
        - nbkchpiprbt | length > 0
        - nbkchpiprbt[0].startswith('172.13.')
      register: hosts_update
  become: true