---
- block:
    # - name: Obtener IP Robótica o Datos para definir el sufijo del cliente
    #   set_fact:
    #     nbkchpiprbt: >-
    #       {{
    #         ansible_all_ipv4_addresses
    #         | select('regex', '^172[.](10|11|13)[.]')
    #         | list
    #       }}

    - name: Actualizar /etc/hosts para equipos sin IP Robótica (150.100.x.x)
      blockinfile:
        path: "{{ filehosts }}"
        marker: "# {mark} ANSIBLE MANAGED NETBACKUP CFS DATA IP"
        block: |
          150.100.246.180 vxnbucfs
          150.100.230.208 cpdnbumedia3-le
          150.80.8.37     lvprpbckrescc01-cfs
          {{ ansible_default_ipv4.address }} {{ nbcltsfx }}
      when: nbkchpiprbt | length == 0
      register: hosts_update_150_xxx
  become: true

- name: Consolidar resultado de modificación en /etc/hosts
  ansible.builtin.set_fact:
    hosts_update: "{{ hosts_update_150_xxx if hosts_update_150_xxx.changed }}"